-- Demo catalog. Products are invented; prices are in USD cents.

INSERT INTO categories (slug, name) VALUES
    ('electronics', 'Electronics'),
    ('home-kitchen', 'Home & Kitchen'),
    ('fashion', 'Fashion'),
    ('sports-outdoors', 'Sports & Outdoors'),
    ('books-stationery', 'Books & Stationery'),
    ('toys-games', 'Toys & Games');

INSERT INTO products (slug, name, description, category_id, price_cents, stock) VALUES
    ('wireless-earbuds', 'Wireless Earbuds',
     'Bluetooth 5.3 earbuds with active noise cancellation and a 30-hour charging case.',
     (SELECT id FROM categories WHERE slug = 'electronics'), 5900, 42),
    ('mechanical-keyboard', 'Compact Mechanical Keyboard',
     'A 75% hot-swappable keyboard with tactile switches and USB-C.',
     (SELECT id FROM categories WHERE slug = 'electronics'), 8900, 18),
    ('portable-power-bank', 'Portable Power Bank 20,000mAh',
     'Charges a phone four times over, with 45W USB-C fast charging.',
     (SELECT id FROM categories WHERE slug = 'electronics'), 3900, 60),
    ('smart-desk-lamp', 'Smart LED Desk Lamp',
     'Adjustable color temperature, a built-in wireless charger, and app control.',
     (SELECT id FROM categories WHERE slug = 'electronics'), 4900, 5),
    ('pour-over-coffee-set', 'Pour-Over Coffee Set',
     'A glass carafe, stainless dripper, and 100 paper filters for slow mornings.',
     (SELECT id FROM categories WHERE slug = 'home-kitchen'), 3400, 30),
    ('cast-iron-skillet', 'Cast Iron Skillet 10"',
     'Pre-seasoned and oven-safe. Gets better the more you cook with it.',
     (SELECT id FROM categories WHERE slug = 'home-kitchen'), 2900, 25),
    ('linen-throw-blanket', 'Linen Throw Blanket',
     'Stonewashed linen that softens with every wash. 130 x 170 cm.',
     (SELECT id FROM categories WHERE slug = 'home-kitchen'), 6500, 14),
    ('glass-food-containers', 'Glass Food Containers (5 pack)',
     'Oven, microwave, and dishwasher safe, with leak-proof locking lids.',
     (SELECT id FROM categories WHERE slug = 'home-kitchen'), 3200, 48),
    ('canvas-tote-bag', 'Heavy Canvas Tote Bag',
     'A roomy 16 oz canvas tote with an inner zip pocket.',
     (SELECT id FROM categories WHERE slug = 'fashion'), 2400, 55),
    ('everyday-sneakers', 'Everyday Knit Sneakers',
     'Lightweight, breathable knit sneakers with a cushioned sole.',
     (SELECT id FROM categories WHERE slug = 'fashion'), 7400, 20),
    ('merino-crew-socks', 'Merino Crew Socks (3 pairs)',
     'Soft merino wool socks that stay warm and fresh on long days.',
     (SELECT id FROM categories WHERE slug = 'fashion'), 2200, 70),
    ('insulated-water-bottle', 'Insulated Water Bottle 750ml',
     'Keeps drinks cold for 24 hours or hot for 12. Leak-proof lid.',
     (SELECT id FROM categories WHERE slug = 'sports-outdoors'), 2800, 65),
    ('yoga-mat', 'Non-Slip Yoga Mat',
     'A 6mm cushioned mat with alignment lines and a carry strap.',
     (SELECT id FROM categories WHERE slug = 'sports-outdoors'), 3600, 33),
    ('trail-daypack', 'Trail Daypack 22L',
     'A light, water-resistant daypack with a hydration sleeve.',
     (SELECT id FROM categories WHERE slug = 'sports-outdoors'), 6900, 8),
    ('resistance-bands', 'Resistance Band Set',
     'Five bands from light to extra heavy, with handles and a door anchor.',
     (SELECT id FROM categories WHERE slug = 'sports-outdoors'), 2500, 0),
    ('dotted-notebook', 'Dotted Hardcover Notebook',
     '192 numbered pages of 100gsm paper that won''t bleed through.',
     (SELECT id FROM categories WHERE slug = 'books-stationery'), 1800, 80),
    ('fountain-pen', 'Everyday Fountain Pen',
     'A smooth medium nib with a converter and five ink cartridges.',
     (SELECT id FROM categories WHERE slug = 'books-stationery'), 2600, 22),
    ('world-cookbook', 'Weeknight Cooking Around the World',
     'Ninety recipes from twenty countries, each ready in under 40 minutes.',
     (SELECT id FROM categories WHERE slug = 'books-stationery'), 3200, 16),
    ('wooden-puzzle-box', 'Wooden Puzzle Box',
     'A handcrafted puzzle box with a hidden compartment and 12 steps to open.',
     (SELECT id FROM categories WHERE slug = 'toys-games'), 3000, 12),
    ('strategy-board-game', 'Harbor Traders Board Game',
     'A 2-4 player strategy game of trading routes and ports. About 60 minutes.',
     (SELECT id FROM categories WHERE slug = 'toys-games'), 4500, 27);
